Modify job2 to include a failing action step
Updated the second action step to fail intentionally.

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -20,7 +20,8 @@ jobs:
     name: echo bye world 2
     runs-on: ubuntu-latest
     steps:
-        -name: bye world action step 1
-         run: echo "bye, world! 1"
-        -name: bye world action step 2
-         run: echo "bye, world! 2"
+        - name: bye world action step 1
+          run: echo "bye, world! 1"
+        - name: bye world action step 2 |
+          run: echo "fail, world! 2"
+               exit 1
